### ISSUE TITLE
Version should be ncarenv?

### ISSUE THREAD

**Issue by vanderwb** [NCAR/csg-spack-downstreams#1]
Currently, the script clones Spack into `/glade/work/$USER/spack-<spack-version>`. But this is a problem when multiple *ncarenv* versions use the same Spack version. To avoid name collisions, I propose defaulting to the following instead:

```
/glade/work/$USER/spack-downstreams/<ncarenv-version>
```

**Comment by mtrahan41** [comment]
Added an option for users to select their specific ncarenv version. Still woking out posted command to ensure commit is exact

**Comment by vanderwb** [comment]
Can it default to the one in the loaded module, if nothing is selected via the option? The module will set a variable that can be used: `$NCAR_ENV_VERSION`

**Comment by mtrahan41** [comment]
Yes! It should already default to the module loaded. Also added support for specific git commit.
