### ISSUE TITLE
Path collisions

### ISSUE THREAD

**Issue by vanderwb** [NCAR/csg-spack-downstreams#2]
The script doesn't seem to be aware of a path collision:
```
fatal: destination path '/glade/work/vanderwb/spack-2' already exists and is not an empty directory.
Spack has been successfully installed and configure for upstream use in: /glade/work/vanderwb/spack-2
```
Even though this technically works out, it would be better if the script checks for a path collision and doesn't try the clone at all.

**Comment by mtrahan41** [comment]
Collision Checking has been added to the script, thanks for the feedback!
