### ISSUE TITLE
Multiple bashrc modifications

### ISSUE THREAD

**Issue by vanderwb** [NCAR/csg-spack-downstreams#3]
If I have multiple upstreams, the script will try to add the `setup-env.sh` from each one to my bashrc, even if others have already edited the bashrc. This will *probably* work out, with the last one defined taking precedence. But it would be cleaner if the script noticed that there was already an upstream spack initialized in the bashrc and ask whether the user wishes to overwrite it. That would keep us from adding a lot of cruft to a user's bashrc as well.

**Comment by mtrahan41** [comment]
Added an option to skip or replace when detecting existing bashrc modifications.
