### ISSUE TITLE
Prevent spack from using "local" config

### ISSUE THREAD

**Issue by vanderwb** [NCAR/csg-spack-downstreams#5]
By default, if you use Spack commands to modify config settings in your downstream, it will place those settings in `~/.spack/*.yaml`. This is (IMO) confusing and will lead to setting clashes if users have multiple downstreams (or just other Spack instances).

I suggest adding this line to the bashrc injection:

```
SPACK_DISABLE_LOCAL_CONFIG=true
```

A note can be printed letting the user know that this setting is getting added, so that folks won't be surprised if they are familiar with the default Spack behavior.

**Comment by mtrahan41** [comment]
Added this variable into bashrc injection
