### ISSUE TITLE
Copy module config and set a modules root

### ISSUE THREAD

**Issue by vanderwb** [NCAR/csg-spack-downstreams#6]
Currently the `modules.yaml` is not copied from the upstream to the downstream. Please copy this file when cloning and add an lmod root to the copied file. This can be done either via a sed replace or you can setup the Spack clone in the shell and run:

```
spack config add "modules:default:roots:lmod:/glade/work/$USER/spack-downstreams/modules/$NCAR_ENV_VERSION"
```

**Comment by vanderwb** [comment]
The `config.yaml` file is also missing in the clone.

**Comment by mtrahan41** [comment]
Need to do more testing with config.yaml, but modules have been added

**Comment by vanderwb** [comment]
The modules part looks good. I've added the config.yaml in a PR just now. If that looks good to you, we can probably close this issue.
